apiVersion: v1
kind: Pod
metadata:
  name: pod-myapp2
  namespace: <prenom>-test2
  labels:
    app: MyApp
    tier: frontend
spec:
  containers:
    - name: myapp-container
      image: nginxdemos/hello:latest
      
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo  `date +"%Y-%m-%d %T"` "Waiting for some dependancies" && sleep 3 ; done']
 