apiVersion: v1
kind: Service
metadata:
  name: service-myapp-loadbalancer
  namespace: studentx-test2
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: MyApp
    tier: frontend
