apiVersion: v1
kind: Service
metadata:
  name: service-myapp-nodeport
  namespace: <prenom>-test2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: MyApp
    tier: frontend
  
