kind: Service
apiVersion: v1
metadata:
  name: service-elasticsearch
  namespace: estest-<prenom>
  labels:
    app: kube-logging
    tier: elasticsearch
spec:
  selector:
    app: kube-logging
    tier: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
