apiVersion: v1
kind: Pod
metadata:
  name: app-consuming-pvc-readwritemany
spec:
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: longhornpvc
  containers:
  - image: alpine
    name: app
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 60; done;"]
    volumeMounts:
      - mountPath: "/mnt/data"
        name: app-storage
