apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myapp-helloworld
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ required ".Values.host entry is required!" .Values.host }}
    secretName: secret-myapp-helloworld
  rules:
  # host rule will route traffic when the hostname requested matches
  - host: {{ required ".Values.host entry is required!" .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-myapp-helloworld
            port:
              number: 80

